# Copyright © 2023 OpenIM open source community. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image:
  repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-api
  pullPolicy: Always
  tag: "dev"
admin-rpc:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/admin-rpc
    pullPolicy: Always
    tag: "dev"
chat-api:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/chat-api
    pullPolicy: Always
    tag: "dev"
chat-rpc:
  image:
    repository: registry.cn-shenzhen.aliyuncs.com/huanglin_hub/chat-rpc
    pullPolicy: Always
    tag: "dev"

config:
  envs:
    discovery: k8s
  zookeeper:
    schema: openim
    zkAddr:
      - 127.0.0.1:12181
    username: ""
    password: ""

  chatApi:
    openImChatApiPort: [ 80 ]
    listenIP:

  adminApi:
    openImAdminApiPort: [ 80 ]
    listenIP:

  rpc:
    registerIP:                            
    listenIP:                               

  rpcPort:
    openImAdminPort: [ 80 ]
    openImChatPort: [ 80 ]
  rpcRegisterName:
    openImAdminName: openimchat-admin-rpc:80
    openImChatName: openimchat-chat-rpc:80

  
  mysql:
    address: [ im-mysql:3306 ]            
    username: root                          
    password: openIM123                     
    #database: openIM_v2                     
    maxOpenConn: 1000                       
    maxIdleConn: 100                       
    maxLifeTime: 60                         
    logLevel: 4                             
    slowThreshold: 500                      
    database: openim_enterprise

 
  log:
    storageLocation: ../_output/logs/           
    rotationTime: 24                    
    remainRotationCount: 2              
    remainLogLevel: 6                   
    isStdout: true
    isJson: false
    withStack: false

  secret: openIM123
  chatSecret: openIM123

  tokenPolicy:
    expire: 86400

  verifyCode:
    validTime: 300 
    validCount: 5 
    uintTime: 86400 
    maxCount: 10 
    superCode: "666666" 
    len: 6 
    use: "" 
    ali:
      endpoint: "dysmsapi.aliyuncs.com"
      accessKeyId: ""
      accessKeySecret: ""
      signName: ""
      verificationCodeTemplateCode: ""

  
  #proxyHeader: "X-Forwarded-For"

  adminList:
    - adminID: admin1
      nickname: chat1
      imAdmin: openIM123456
    - adminID: admin2
      nickname: chat2
      imAdmin: openIM654321
    - adminID: admin3
      nickname: chat3
      imAdmin: openIMAdmin


  openIMUrl: "http://openimserver-openim-api"

  redis:
    address: [ im-redis-master:6379 ]
    username: ''
    password: openIM123
