# Copyright © 2023 OpenIM. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: OpenIM Chat Start Execute Scripts

on: 
    push:
      branches:
          - main
      paths-ignore:
          - "docs/**"
          - "README.md"
          - "README_zh-CN.md"
          - "CONTRIBUTING.md"
    pull_request:
      branches:
          - main
      paths-ignore:
          - "README.md"
          - "README_zh-CN.md"
          - "CONTRIBUTING.md"
          - "docs/**"

jobs:
  execute-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Install latest Bash (macOS only)
    #   if: runner.os == 'macOS'
    #   run: |
    #     /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    #     brew update
    
    #     brew install bash
    #     brew install gnu-sed
    
    #     echo "/usr/local/bin" >> $GITHUB_PATH
    #     echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH

    #     brew install --cask docker
    #     open /Applications/Docker.app

    - name: deploy all services
      run: |
        git clone https://github.com/openimsdk/open-im-server.git
        cd open-im-server
        sudo docker compose up -d
        sudo sleep 30

        sudo bash bootstrap.sh
        sudo mage
        sudo mage start
        sudo mage check

        echo "pwd = $(pwd)"
        cd ..
        ls -al && pwd
      shell: bash
      continue-on-error: true

    - name: Build Chat
      run: |
        sudo bash bootstrap.sh
        sudo mage
        sudo mage start
      shell: bash

    - name: Print chat_$(date '+%Y%m%d').log
      run: |
        ls -al && echo "pwd = $(pwd)"
      shell: bash
      continue-on-error: true
